general:
  dataset: calhousing
  api_key:

eval_params:
  model: ft:gpt-3.5-turbo-0125:personal::96gYoXJr #gpt-3.5-turbo-0125
  max_tokens: 128
  temperature: 0.1
  top_p: 1

finetune:
  seed: 0
  numshot: 0
  model: gpt-3.5-turbo-0125
